version: '3.8'
services:
  chat-main:
    image: maneav78/chat-back:latest
    container_name: chat-main-dc
    ports:
      - "5000:5000"
    networks:
      - chat-network
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGODB_URI=${MONGODB_URI}
  
  chat-vue:
    image: maneav78/chat-front:latest
    container_name: chat-vue-dc
    ports:
      - "8080:8080"
    networks:
      - chat-network

  test-script:
    image: maneav78/chat-test:latest
    container_name: test-script-dc
    networks:
      - chat-network
    depends_on:
      - chat-main

networks:
  chat-network:
    driver: bridge
