apiVersion: v1
kind: Namespace
metadata:
  name: my-chat-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-front
  namespace: my-chat-app
  labels:
    app: chat-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-front
  template:
    metadata:
      labels:
        app: chat-front
    spec:
      containers:
      - name: chat-front
        image: DOCKER_USERNAME/chat-front:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: chat-front
  namespace: my-chat-app
spec:
  type: LoadBalancer
  selector:
    app: chat-front
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-back
  namespace: my-chat-app
  labels:
    app: chat-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-back
  template:
    metadata:
      labels:
        app: chat-back
    spec:
      containers:
      - name: chat-back
        image: DOCKER_USERNAME/chat-back:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: MONGO_URI_PLACEHOLDER
        - name: API_KEY
          value: API_KEY_PLACEHOLDER
---
apiVersion: v1
kind: Service
metadata:
  name: chat-back
  namespace: my-chat-app
spec:
  selector:
    app: chat-back
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
